/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as localeRegisterRouteImport } from './routes/($locale)/register'
import { Route as localeLoginRouteImport } from './routes/($locale)/login'
import { Route as localeForgotPasswordRouteImport } from './routes/($locale)/forgot-password'
import { Route as localeDashboardRouteImport } from './routes/($locale)/dashboard'
import { Route as localeAdminRouteImport } from './routes/($locale)/admin'
import { Route as localeMarketingRouteImport } from './routes/($locale)/_marketing'
import { Route as localeProjectsIndexRouteImport } from './routes/($locale)/projects/index'
import { Route as localeDashboardIndexRouteImport } from './routes/($locale)/dashboard/index'
import { Route as localeMarketingIndexRouteImport } from './routes/($locale)/_marketing/index'
import { Route as localeDashboardWalletRouteImport } from './routes/($locale)/dashboard/wallet'
import { Route as localeDashboardTransactionsRouteImport } from './routes/($locale)/dashboard/transactions'
import { Route as localeDashboardStatementsRouteImport } from './routes/($locale)/dashboard/statements'
import { Route as localeDashboardSettingsRouteImport } from './routes/($locale)/dashboard/settings'
import { Route as localeDashboardProgressRouteImport } from './routes/($locale)/dashboard/progress'
import { Route as localeDashboardPortfolioRouteImport } from './routes/($locale)/dashboard/portfolio'
import { Route as localeDashboardNotificationsRouteImport } from './routes/($locale)/dashboard/notifications'
import { Route as localeDashboardKycRouteImport } from './routes/($locale)/dashboard/kyc'
import { Route as localeDashboardInvestmentsRouteImport } from './routes/($locale)/dashboard/investments'
import { Route as localeDashboardFavoritesRouteImport } from './routes/($locale)/dashboard/favorites'
import { Route as localeDashboardDocumentsRouteImport } from './routes/($locale)/dashboard/documents'
import { Route as localeDashboardDistributionsRouteImport } from './routes/($locale)/dashboard/distributions'
import { Route as localeAdminMetricsRouteImport } from './routes/($locale)/admin/metrics'
import { Route as localeAdminInvestorsRouteImport } from './routes/($locale)/admin/investors'
import { Route as localeAdminInvestmentsRouteImport } from './routes/($locale)/admin/investments'
import { Route as localeAdminDocumentsRouteImport } from './routes/($locale)/admin/documents'
import { Route as localeAdminDashboardRouteImport } from './routes/($locale)/admin/dashboard'
import { Route as localeAdminBudgetRouteImport } from './routes/($locale)/admin/budget'
import { Route as localeAdminAuditRouteImport } from './routes/($locale)/admin/audit'
import { Route as localeMarketingHowItWorksRouteImport } from './routes/($locale)/_marketing/how-it-works'
import { Route as localeMarketingAboutRouteImport } from './routes/($locale)/_marketing/about'
import { Route as localeProjectsSlugIndexRouteImport } from './routes/($locale)/projects/$slug/index'
import { Route as localeAdminProjectsIndexRouteImport } from './routes/($locale)/admin/projects/index'
import { Route as localeAdminProjectsIdRouteImport } from './routes/($locale)/admin/projects/$id'
import { Route as localeAdminInvestorsIdRouteImport } from './routes/($locale)/admin/investors/$id'
import { Route as localeProjectsSlugInvestIndexRouteImport } from './routes/($locale)/projects/$slug/invest/index'
import { Route as localeProjectsSlugInvestSuccessRouteImport } from './routes/($locale)/projects/$slug/invest/success'

const localeRegisterRoute = localeRegisterRouteImport.update({
  id: '/($locale)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const localeLoginRoute = localeLoginRouteImport.update({
  id: '/($locale)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const localeForgotPasswordRoute = localeForgotPasswordRouteImport.update({
  id: '/($locale)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const localeDashboardRoute = localeDashboardRouteImport.update({
  id: '/($locale)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const localeAdminRoute = localeAdminRouteImport.update({
  id: '/($locale)/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const localeMarketingRoute = localeMarketingRouteImport.update({
  id: '/($locale)/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const localeProjectsIndexRoute = localeProjectsIndexRouteImport.update({
  id: '/($locale)/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const localeDashboardIndexRoute = localeDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => localeDashboardRoute,
} as any)
const localeMarketingIndexRoute = localeMarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => localeMarketingRoute,
} as any)
const localeDashboardWalletRoute = localeDashboardWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => localeDashboardRoute,
} as any)
const localeDashboardTransactionsRoute =
  localeDashboardTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => localeDashboardRoute,
  } as any)
const localeDashboardStatementsRoute =
  localeDashboardStatementsRouteImport.update({
    id: '/statements',
    path: '/statements',
    getParentRoute: () => localeDashboardRoute,
  } as any)
const localeDashboardSettingsRoute = localeDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => localeDashboardRoute,
} as any)
const localeDashboardProgressRoute = localeDashboardProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => localeDashboardRoute,
} as any)
const localeDashboardPortfolioRoute =
  localeDashboardPortfolioRouteImport.update({
    id: '/portfolio',
    path: '/portfolio',
    getParentRoute: () => localeDashboardRoute,
  } as any)
const localeDashboardNotificationsRoute =
  localeDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => localeDashboardRoute,
  } as any)
const localeDashboardKycRoute = localeDashboardKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => localeDashboardRoute,
} as any)
const localeDashboardInvestmentsRoute =
  localeDashboardInvestmentsRouteImport.update({
    id: '/investments',
    path: '/investments',
    getParentRoute: () => localeDashboardRoute,
  } as any)
const localeDashboardFavoritesRoute =
  localeDashboardFavoritesRouteImport.update({
    id: '/favorites',
    path: '/favorites',
    getParentRoute: () => localeDashboardRoute,
  } as any)
const localeDashboardDocumentsRoute =
  localeDashboardDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => localeDashboardRoute,
  } as any)
const localeDashboardDistributionsRoute =
  localeDashboardDistributionsRouteImport.update({
    id: '/distributions',
    path: '/distributions',
    getParentRoute: () => localeDashboardRoute,
  } as any)
const localeAdminMetricsRoute = localeAdminMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => localeAdminRoute,
} as any)
const localeAdminInvestorsRoute = localeAdminInvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => localeAdminRoute,
} as any)
const localeAdminInvestmentsRoute = localeAdminInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => localeAdminRoute,
} as any)
const localeAdminDocumentsRoute = localeAdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => localeAdminRoute,
} as any)
const localeAdminDashboardRoute = localeAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => localeAdminRoute,
} as any)
const localeAdminBudgetRoute = localeAdminBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => localeAdminRoute,
} as any)
const localeAdminAuditRoute = localeAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => localeAdminRoute,
} as any)
const localeMarketingHowItWorksRoute =
  localeMarketingHowItWorksRouteImport.update({
    id: '/how-it-works',
    path: '/how-it-works',
    getParentRoute: () => localeMarketingRoute,
  } as any)
const localeMarketingAboutRoute = localeMarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => localeMarketingRoute,
} as any)
const localeProjectsSlugIndexRoute = localeProjectsSlugIndexRouteImport.update({
  id: '/($locale)/projects/$slug/',
  path: '/projects/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const localeAdminProjectsIndexRoute =
  localeAdminProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => localeAdminRoute,
  } as any)
const localeAdminProjectsIdRoute = localeAdminProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => localeAdminRoute,
} as any)
const localeAdminInvestorsIdRoute = localeAdminInvestorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => localeAdminInvestorsRoute,
} as any)
const localeProjectsSlugInvestIndexRoute =
  localeProjectsSlugInvestIndexRouteImport.update({
    id: '/($locale)/projects/$slug/invest/',
    path: '/projects/$slug/invest/',
    getParentRoute: () => rootRouteImport,
  } as any)
const localeProjectsSlugInvestSuccessRoute =
  localeProjectsSlugInvestSuccessRouteImport.update({
    id: '/($locale)/projects/$slug/invest/success',
    path: '/projects/$slug/invest/success',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof localeAdminRouteWithChildren
  '/dashboard': typeof localeDashboardRouteWithChildren
  '/forgot-password': typeof localeForgotPasswordRoute
  '/login': typeof localeLoginRoute
  '/register': typeof localeRegisterRoute
  '/about': typeof localeMarketingAboutRoute
  '/how-it-works': typeof localeMarketingHowItWorksRoute
  '/admin/audit': typeof localeAdminAuditRoute
  '/admin/budget': typeof localeAdminBudgetRoute
  '/admin/dashboard': typeof localeAdminDashboardRoute
  '/admin/documents': typeof localeAdminDocumentsRoute
  '/admin/investments': typeof localeAdminInvestmentsRoute
  '/admin/investors': typeof localeAdminInvestorsRouteWithChildren
  '/admin/metrics': typeof localeAdminMetricsRoute
  '/dashboard/distributions': typeof localeDashboardDistributionsRoute
  '/dashboard/documents': typeof localeDashboardDocumentsRoute
  '/dashboard/favorites': typeof localeDashboardFavoritesRoute
  '/dashboard/investments': typeof localeDashboardInvestmentsRoute
  '/dashboard/kyc': typeof localeDashboardKycRoute
  '/dashboard/notifications': typeof localeDashboardNotificationsRoute
  '/dashboard/portfolio': typeof localeDashboardPortfolioRoute
  '/dashboard/progress': typeof localeDashboardProgressRoute
  '/dashboard/settings': typeof localeDashboardSettingsRoute
  '/dashboard/statements': typeof localeDashboardStatementsRoute
  '/dashboard/transactions': typeof localeDashboardTransactionsRoute
  '/dashboard/wallet': typeof localeDashboardWalletRoute
  '/': typeof localeMarketingIndexRoute
  '/dashboard/': typeof localeDashboardIndexRoute
  '/projects/': typeof localeProjectsIndexRoute
  '/admin/investors/$id': typeof localeAdminInvestorsIdRoute
  '/admin/projects/$id': typeof localeAdminProjectsIdRoute
  '/admin/projects/': typeof localeAdminProjectsIndexRoute
  '/projects/$slug/': typeof localeProjectsSlugIndexRoute
  '/projects/$slug/invest/success': typeof localeProjectsSlugInvestSuccessRoute
  '/projects/$slug/invest/': typeof localeProjectsSlugInvestIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof localeAdminRouteWithChildren
  '/forgot-password': typeof localeForgotPasswordRoute
  '/login': typeof localeLoginRoute
  '/register': typeof localeRegisterRoute
  '/about': typeof localeMarketingAboutRoute
  '/how-it-works': typeof localeMarketingHowItWorksRoute
  '/admin/audit': typeof localeAdminAuditRoute
  '/admin/budget': typeof localeAdminBudgetRoute
  '/admin/dashboard': typeof localeAdminDashboardRoute
  '/admin/documents': typeof localeAdminDocumentsRoute
  '/admin/investments': typeof localeAdminInvestmentsRoute
  '/admin/investors': typeof localeAdminInvestorsRouteWithChildren
  '/admin/metrics': typeof localeAdminMetricsRoute
  '/dashboard/distributions': typeof localeDashboardDistributionsRoute
  '/dashboard/documents': typeof localeDashboardDocumentsRoute
  '/dashboard/favorites': typeof localeDashboardFavoritesRoute
  '/dashboard/investments': typeof localeDashboardInvestmentsRoute
  '/dashboard/kyc': typeof localeDashboardKycRoute
  '/dashboard/notifications': typeof localeDashboardNotificationsRoute
  '/dashboard/portfolio': typeof localeDashboardPortfolioRoute
  '/dashboard/progress': typeof localeDashboardProgressRoute
  '/dashboard/settings': typeof localeDashboardSettingsRoute
  '/dashboard/statements': typeof localeDashboardStatementsRoute
  '/dashboard/transactions': typeof localeDashboardTransactionsRoute
  '/dashboard/wallet': typeof localeDashboardWalletRoute
  '/': typeof localeMarketingIndexRoute
  '/dashboard': typeof localeDashboardIndexRoute
  '/projects': typeof localeProjectsIndexRoute
  '/admin/investors/$id': typeof localeAdminInvestorsIdRoute
  '/admin/projects/$id': typeof localeAdminProjectsIdRoute
  '/admin/projects': typeof localeAdminProjectsIndexRoute
  '/projects/$slug': typeof localeProjectsSlugIndexRoute
  '/projects/$slug/invest/success': typeof localeProjectsSlugInvestSuccessRoute
  '/projects/$slug/invest': typeof localeProjectsSlugInvestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/($locale)/_marketing': typeof localeMarketingRouteWithChildren
  '/($locale)/admin': typeof localeAdminRouteWithChildren
  '/($locale)/dashboard': typeof localeDashboardRouteWithChildren
  '/($locale)/forgot-password': typeof localeForgotPasswordRoute
  '/($locale)/login': typeof localeLoginRoute
  '/($locale)/register': typeof localeRegisterRoute
  '/($locale)/_marketing/about': typeof localeMarketingAboutRoute
  '/($locale)/_marketing/how-it-works': typeof localeMarketingHowItWorksRoute
  '/($locale)/admin/audit': typeof localeAdminAuditRoute
  '/($locale)/admin/budget': typeof localeAdminBudgetRoute
  '/($locale)/admin/dashboard': typeof localeAdminDashboardRoute
  '/($locale)/admin/documents': typeof localeAdminDocumentsRoute
  '/($locale)/admin/investments': typeof localeAdminInvestmentsRoute
  '/($locale)/admin/investors': typeof localeAdminInvestorsRouteWithChildren
  '/($locale)/admin/metrics': typeof localeAdminMetricsRoute
  '/($locale)/dashboard/distributions': typeof localeDashboardDistributionsRoute
  '/($locale)/dashboard/documents': typeof localeDashboardDocumentsRoute
  '/($locale)/dashboard/favorites': typeof localeDashboardFavoritesRoute
  '/($locale)/dashboard/investments': typeof localeDashboardInvestmentsRoute
  '/($locale)/dashboard/kyc': typeof localeDashboardKycRoute
  '/($locale)/dashboard/notifications': typeof localeDashboardNotificationsRoute
  '/($locale)/dashboard/portfolio': typeof localeDashboardPortfolioRoute
  '/($locale)/dashboard/progress': typeof localeDashboardProgressRoute
  '/($locale)/dashboard/settings': typeof localeDashboardSettingsRoute
  '/($locale)/dashboard/statements': typeof localeDashboardStatementsRoute
  '/($locale)/dashboard/transactions': typeof localeDashboardTransactionsRoute
  '/($locale)/dashboard/wallet': typeof localeDashboardWalletRoute
  '/($locale)/_marketing/': typeof localeMarketingIndexRoute
  '/($locale)/dashboard/': typeof localeDashboardIndexRoute
  '/($locale)/projects/': typeof localeProjectsIndexRoute
  '/($locale)/admin/investors/$id': typeof localeAdminInvestorsIdRoute
  '/($locale)/admin/projects/$id': typeof localeAdminProjectsIdRoute
  '/($locale)/admin/projects/': typeof localeAdminProjectsIndexRoute
  '/($locale)/projects/$slug/': typeof localeProjectsSlugIndexRoute
  '/($locale)/projects/$slug/invest/success': typeof localeProjectsSlugInvestSuccessRoute
  '/($locale)/projects/$slug/invest/': typeof localeProjectsSlugInvestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/about'
    | '/how-it-works'
    | '/admin/audit'
    | '/admin/budget'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/investments'
    | '/admin/investors'
    | '/admin/metrics'
    | '/dashboard/distributions'
    | '/dashboard/documents'
    | '/dashboard/favorites'
    | '/dashboard/investments'
    | '/dashboard/kyc'
    | '/dashboard/notifications'
    | '/dashboard/portfolio'
    | '/dashboard/progress'
    | '/dashboard/settings'
    | '/dashboard/statements'
    | '/dashboard/transactions'
    | '/dashboard/wallet'
    | '/'
    | '/dashboard/'
    | '/projects/'
    | '/admin/investors/$id'
    | '/admin/projects/$id'
    | '/admin/projects/'
    | '/projects/$slug/'
    | '/projects/$slug/invest/success'
    | '/projects/$slug/invest/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/about'
    | '/how-it-works'
    | '/admin/audit'
    | '/admin/budget'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/investments'
    | '/admin/investors'
    | '/admin/metrics'
    | '/dashboard/distributions'
    | '/dashboard/documents'
    | '/dashboard/favorites'
    | '/dashboard/investments'
    | '/dashboard/kyc'
    | '/dashboard/notifications'
    | '/dashboard/portfolio'
    | '/dashboard/progress'
    | '/dashboard/settings'
    | '/dashboard/statements'
    | '/dashboard/transactions'
    | '/dashboard/wallet'
    | '/'
    | '/dashboard'
    | '/projects'
    | '/admin/investors/$id'
    | '/admin/projects/$id'
    | '/admin/projects'
    | '/projects/$slug'
    | '/projects/$slug/invest/success'
    | '/projects/$slug/invest'
  id:
    | '__root__'
    | '/($locale)/_marketing'
    | '/($locale)/admin'
    | '/($locale)/dashboard'
    | '/($locale)/forgot-password'
    | '/($locale)/login'
    | '/($locale)/register'
    | '/($locale)/_marketing/about'
    | '/($locale)/_marketing/how-it-works'
    | '/($locale)/admin/audit'
    | '/($locale)/admin/budget'
    | '/($locale)/admin/dashboard'
    | '/($locale)/admin/documents'
    | '/($locale)/admin/investments'
    | '/($locale)/admin/investors'
    | '/($locale)/admin/metrics'
    | '/($locale)/dashboard/distributions'
    | '/($locale)/dashboard/documents'
    | '/($locale)/dashboard/favorites'
    | '/($locale)/dashboard/investments'
    | '/($locale)/dashboard/kyc'
    | '/($locale)/dashboard/notifications'
    | '/($locale)/dashboard/portfolio'
    | '/($locale)/dashboard/progress'
    | '/($locale)/dashboard/settings'
    | '/($locale)/dashboard/statements'
    | '/($locale)/dashboard/transactions'
    | '/($locale)/dashboard/wallet'
    | '/($locale)/_marketing/'
    | '/($locale)/dashboard/'
    | '/($locale)/projects/'
    | '/($locale)/admin/investors/$id'
    | '/($locale)/admin/projects/$id'
    | '/($locale)/admin/projects/'
    | '/($locale)/projects/$slug/'
    | '/($locale)/projects/$slug/invest/success'
    | '/($locale)/projects/$slug/invest/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  localeMarketingRoute: typeof localeMarketingRouteWithChildren
  localeAdminRoute: typeof localeAdminRouteWithChildren
  localeDashboardRoute: typeof localeDashboardRouteWithChildren
  localeForgotPasswordRoute: typeof localeForgotPasswordRoute
  localeLoginRoute: typeof localeLoginRoute
  localeRegisterRoute: typeof localeRegisterRoute
  localeProjectsIndexRoute: typeof localeProjectsIndexRoute
  localeProjectsSlugIndexRoute: typeof localeProjectsSlugIndexRoute
  localeProjectsSlugInvestSuccessRoute: typeof localeProjectsSlugInvestSuccessRoute
  localeProjectsSlugInvestIndexRoute: typeof localeProjectsSlugInvestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/($locale)/register': {
      id: '/($locale)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof localeRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/($locale)/login': {
      id: '/($locale)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof localeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/($locale)/forgot-password': {
      id: '/($locale)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof localeForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/($locale)/dashboard': {
      id: '/($locale)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof localeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/($locale)/admin': {
      id: '/($locale)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof localeAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/($locale)/_marketing': {
      id: '/($locale)/_marketing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof localeMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/($locale)/projects/': {
      id: '/($locale)/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof localeProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/($locale)/dashboard/': {
      id: '/($locale)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof localeDashboardIndexRouteImport
      parentRoute: typeof localeDashboardRoute
    }
    '/($locale)/_marketing/': {
      id: '/($locale)/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof localeMarketingIndexRouteImport
      parentRoute: typeof localeMarketingRoute
    }
    '/($locale)/dashboard/wallet': {
      id: '/($locale)/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof localeDashboardWalletRouteImport
      parentRoute: typeof localeDashboardRoute
    }
    '/($locale)/dashboard/transactions': {
      id: '/($locale)/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof localeDashboardTransactionsRouteImport
      parentRoute: typeof localeDashboardRoute
    }
    '/($locale)/dashboard/statements': {
      id: '/($locale)/dashboard/statements'
      path: '/statements'
      fullPath: '/dashboard/statements'
      preLoaderRoute: typeof localeDashboardStatementsRouteImport
      parentRoute: typeof localeDashboardRoute
    }
    '/($locale)/dashboard/settings': {
      id: '/($locale)/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof localeDashboardSettingsRouteImport
      parentRoute: typeof localeDashboardRoute
    }
    '/($locale)/dashboard/progress': {
      id: '/($locale)/dashboard/progress'
      path: '/progress'
      fullPath: '/dashboard/progress'
      preLoaderRoute: typeof localeDashboardProgressRouteImport
      parentRoute: typeof localeDashboardRoute
    }
    '/($locale)/dashboard/portfolio': {
      id: '/($locale)/dashboard/portfolio'
      path: '/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof localeDashboardPortfolioRouteImport
      parentRoute: typeof localeDashboardRoute
    }
    '/($locale)/dashboard/notifications': {
      id: '/($locale)/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof localeDashboardNotificationsRouteImport
      parentRoute: typeof localeDashboardRoute
    }
    '/($locale)/dashboard/kyc': {
      id: '/($locale)/dashboard/kyc'
      path: '/kyc'
      fullPath: '/dashboard/kyc'
      preLoaderRoute: typeof localeDashboardKycRouteImport
      parentRoute: typeof localeDashboardRoute
    }
    '/($locale)/dashboard/investments': {
      id: '/($locale)/dashboard/investments'
      path: '/investments'
      fullPath: '/dashboard/investments'
      preLoaderRoute: typeof localeDashboardInvestmentsRouteImport
      parentRoute: typeof localeDashboardRoute
    }
    '/($locale)/dashboard/favorites': {
      id: '/($locale)/dashboard/favorites'
      path: '/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof localeDashboardFavoritesRouteImport
      parentRoute: typeof localeDashboardRoute
    }
    '/($locale)/dashboard/documents': {
      id: '/($locale)/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof localeDashboardDocumentsRouteImport
      parentRoute: typeof localeDashboardRoute
    }
    '/($locale)/dashboard/distributions': {
      id: '/($locale)/dashboard/distributions'
      path: '/distributions'
      fullPath: '/dashboard/distributions'
      preLoaderRoute: typeof localeDashboardDistributionsRouteImport
      parentRoute: typeof localeDashboardRoute
    }
    '/($locale)/admin/metrics': {
      id: '/($locale)/admin/metrics'
      path: '/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof localeAdminMetricsRouteImport
      parentRoute: typeof localeAdminRoute
    }
    '/($locale)/admin/investors': {
      id: '/($locale)/admin/investors'
      path: '/investors'
      fullPath: '/admin/investors'
      preLoaderRoute: typeof localeAdminInvestorsRouteImport
      parentRoute: typeof localeAdminRoute
    }
    '/($locale)/admin/investments': {
      id: '/($locale)/admin/investments'
      path: '/investments'
      fullPath: '/admin/investments'
      preLoaderRoute: typeof localeAdminInvestmentsRouteImport
      parentRoute: typeof localeAdminRoute
    }
    '/($locale)/admin/documents': {
      id: '/($locale)/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof localeAdminDocumentsRouteImport
      parentRoute: typeof localeAdminRoute
    }
    '/($locale)/admin/dashboard': {
      id: '/($locale)/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof localeAdminDashboardRouteImport
      parentRoute: typeof localeAdminRoute
    }
    '/($locale)/admin/budget': {
      id: '/($locale)/admin/budget'
      path: '/budget'
      fullPath: '/admin/budget'
      preLoaderRoute: typeof localeAdminBudgetRouteImport
      parentRoute: typeof localeAdminRoute
    }
    '/($locale)/admin/audit': {
      id: '/($locale)/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof localeAdminAuditRouteImport
      parentRoute: typeof localeAdminRoute
    }
    '/($locale)/_marketing/how-it-works': {
      id: '/($locale)/_marketing/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof localeMarketingHowItWorksRouteImport
      parentRoute: typeof localeMarketingRoute
    }
    '/($locale)/_marketing/about': {
      id: '/($locale)/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof localeMarketingAboutRouteImport
      parentRoute: typeof localeMarketingRoute
    }
    '/($locale)/projects/$slug/': {
      id: '/($locale)/projects/$slug/'
      path: '/projects/$slug'
      fullPath: '/projects/$slug/'
      preLoaderRoute: typeof localeProjectsSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/($locale)/admin/projects/': {
      id: '/($locale)/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof localeAdminProjectsIndexRouteImport
      parentRoute: typeof localeAdminRoute
    }
    '/($locale)/admin/projects/$id': {
      id: '/($locale)/admin/projects/$id'
      path: '/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof localeAdminProjectsIdRouteImport
      parentRoute: typeof localeAdminRoute
    }
    '/($locale)/admin/investors/$id': {
      id: '/($locale)/admin/investors/$id'
      path: '/$id'
      fullPath: '/admin/investors/$id'
      preLoaderRoute: typeof localeAdminInvestorsIdRouteImport
      parentRoute: typeof localeAdminInvestorsRoute
    }
    '/($locale)/projects/$slug/invest/': {
      id: '/($locale)/projects/$slug/invest/'
      path: '/projects/$slug/invest'
      fullPath: '/projects/$slug/invest/'
      preLoaderRoute: typeof localeProjectsSlugInvestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/($locale)/projects/$slug/invest/success': {
      id: '/($locale)/projects/$slug/invest/success'
      path: '/projects/$slug/invest/success'
      fullPath: '/projects/$slug/invest/success'
      preLoaderRoute: typeof localeProjectsSlugInvestSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface localeMarketingRouteChildren {
  localeMarketingAboutRoute: typeof localeMarketingAboutRoute
  localeMarketingHowItWorksRoute: typeof localeMarketingHowItWorksRoute
  localeMarketingIndexRoute: typeof localeMarketingIndexRoute
}

const localeMarketingRouteChildren: localeMarketingRouteChildren = {
  localeMarketingAboutRoute: localeMarketingAboutRoute,
  localeMarketingHowItWorksRoute: localeMarketingHowItWorksRoute,
  localeMarketingIndexRoute: localeMarketingIndexRoute,
}

const localeMarketingRouteWithChildren = localeMarketingRoute._addFileChildren(
  localeMarketingRouteChildren,
)

interface localeAdminInvestorsRouteChildren {
  localeAdminInvestorsIdRoute: typeof localeAdminInvestorsIdRoute
}

const localeAdminInvestorsRouteChildren: localeAdminInvestorsRouteChildren = {
  localeAdminInvestorsIdRoute: localeAdminInvestorsIdRoute,
}

const localeAdminInvestorsRouteWithChildren =
  localeAdminInvestorsRoute._addFileChildren(localeAdminInvestorsRouteChildren)

interface localeAdminRouteChildren {
  localeAdminAuditRoute: typeof localeAdminAuditRoute
  localeAdminBudgetRoute: typeof localeAdminBudgetRoute
  localeAdminDashboardRoute: typeof localeAdminDashboardRoute
  localeAdminDocumentsRoute: typeof localeAdminDocumentsRoute
  localeAdminInvestmentsRoute: typeof localeAdminInvestmentsRoute
  localeAdminInvestorsRoute: typeof localeAdminInvestorsRouteWithChildren
  localeAdminMetricsRoute: typeof localeAdminMetricsRoute
  localeAdminProjectsIdRoute: typeof localeAdminProjectsIdRoute
  localeAdminProjectsIndexRoute: typeof localeAdminProjectsIndexRoute
}

const localeAdminRouteChildren: localeAdminRouteChildren = {
  localeAdminAuditRoute: localeAdminAuditRoute,
  localeAdminBudgetRoute: localeAdminBudgetRoute,
  localeAdminDashboardRoute: localeAdminDashboardRoute,
  localeAdminDocumentsRoute: localeAdminDocumentsRoute,
  localeAdminInvestmentsRoute: localeAdminInvestmentsRoute,
  localeAdminInvestorsRoute: localeAdminInvestorsRouteWithChildren,
  localeAdminMetricsRoute: localeAdminMetricsRoute,
  localeAdminProjectsIdRoute: localeAdminProjectsIdRoute,
  localeAdminProjectsIndexRoute: localeAdminProjectsIndexRoute,
}

const localeAdminRouteWithChildren = localeAdminRoute._addFileChildren(
  localeAdminRouteChildren,
)

interface localeDashboardRouteChildren {
  localeDashboardDistributionsRoute: typeof localeDashboardDistributionsRoute
  localeDashboardDocumentsRoute: typeof localeDashboardDocumentsRoute
  localeDashboardFavoritesRoute: typeof localeDashboardFavoritesRoute
  localeDashboardInvestmentsRoute: typeof localeDashboardInvestmentsRoute
  localeDashboardKycRoute: typeof localeDashboardKycRoute
  localeDashboardNotificationsRoute: typeof localeDashboardNotificationsRoute
  localeDashboardPortfolioRoute: typeof localeDashboardPortfolioRoute
  localeDashboardProgressRoute: typeof localeDashboardProgressRoute
  localeDashboardSettingsRoute: typeof localeDashboardSettingsRoute
  localeDashboardStatementsRoute: typeof localeDashboardStatementsRoute
  localeDashboardTransactionsRoute: typeof localeDashboardTransactionsRoute
  localeDashboardWalletRoute: typeof localeDashboardWalletRoute
  localeDashboardIndexRoute: typeof localeDashboardIndexRoute
}

const localeDashboardRouteChildren: localeDashboardRouteChildren = {
  localeDashboardDistributionsRoute: localeDashboardDistributionsRoute,
  localeDashboardDocumentsRoute: localeDashboardDocumentsRoute,
  localeDashboardFavoritesRoute: localeDashboardFavoritesRoute,
  localeDashboardInvestmentsRoute: localeDashboardInvestmentsRoute,
  localeDashboardKycRoute: localeDashboardKycRoute,
  localeDashboardNotificationsRoute: localeDashboardNotificationsRoute,
  localeDashboardPortfolioRoute: localeDashboardPortfolioRoute,
  localeDashboardProgressRoute: localeDashboardProgressRoute,
  localeDashboardSettingsRoute: localeDashboardSettingsRoute,
  localeDashboardStatementsRoute: localeDashboardStatementsRoute,
  localeDashboardTransactionsRoute: localeDashboardTransactionsRoute,
  localeDashboardWalletRoute: localeDashboardWalletRoute,
  localeDashboardIndexRoute: localeDashboardIndexRoute,
}

const localeDashboardRouteWithChildren = localeDashboardRoute._addFileChildren(
  localeDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  localeMarketingRoute: localeMarketingRouteWithChildren,
  localeAdminRoute: localeAdminRouteWithChildren,
  localeDashboardRoute: localeDashboardRouteWithChildren,
  localeForgotPasswordRoute: localeForgotPasswordRoute,
  localeLoginRoute: localeLoginRoute,
  localeRegisterRoute: localeRegisterRoute,
  localeProjectsIndexRoute: localeProjectsIndexRoute,
  localeProjectsSlugIndexRoute: localeProjectsSlugIndexRoute,
  localeProjectsSlugInvestSuccessRoute: localeProjectsSlugInvestSuccessRoute,
  localeProjectsSlugInvestIndexRoute: localeProjectsSlugInvestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
